### ISSUE TITLE
Upgrade to Webpack 4

### ISSUE THREAD

**Issue by chris-pearce** [chris-pearce/scotts-site#9]

**Comment by nbkhope** [comment]
Hi, I can help you out, but I could not find webpack in the `package.json` file. How are you using it?

**Comment by chris-pearce** [comment]
Hi, thanks for the offer and sorry about late response, I totally missed your comment!

This site is a [Gatsby](https://www.gatsbyjs.org/) site so the Webpack config comes from there. Get you started: https://www.google.com.au/search?q=upgrading+Gatsby+Webpack&oq=upgrading+Gatsby+Webpack&aqs=chrome..69i57.5964j0j7&sourceid=chrome&ie=UTF-8.
